config/routes.rb
PtolemyWeb::Application.routes.draw do

  resources :replacements

  resources :hardwares

  @pcre = /[0-9A-Za-z\-\.\,\\\_\(\)\|\*\$\"\']+/
  @id = /[0-9A-Za-z]+/
  @mac = /[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}/
  @ip = /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/

  get '/devices/list', to: 'devices#list', :as => 'device_list'
  get '/devices/?(:device)?', to: 'devices#index', :constraints => { :device => @pcre }
  get '/devices', to: 'devices#index', :as => 'devices'
  get '/api/devices/neighbours', to: 'devices#api_device_neighbours', :as => 'api_device_neighbours'
  get '/api/devices/ipsla', to: 'devices#api_device_ipsla', :as => 'api_device_ipsla'
  get '/api/devices/vlans', to: 'devices#api_device_vlans', :as => 'api_device_vlans'
  get '/api/devices/list', to: 'devices#api_devices', :as => 'autocomplete_device_list'

  get '/ports/by_utilisation', to: 'ports#port_graphs_by_device', :constraints => { :device => @pcre }, :as => 'port_graphs_by_device'
  get '/ports/by_utilisation/:device', to: 'ports#port_graphs_by_device', :constraints => { :device => @pcre }
  get '/ports/by_uplinks', to: 'ports#port_graphs_by_uplinks', :constraints => { :device => @pcre }, :as => 'port_graphs_by_uplinks'

  get '/ports/location', to: 'ports#location', :as => 'port_location'
  get '/ports/:device', to: 'ports#index', :constraints => { :device => @pcre }
  get '/ports', to: 'ports#index', :constraints => { :device => @pcre }, :as => 'network_ports'

  get '/api/ports/neighbours', to: 'ports#api_port_neighbours', :as => 'api_port_neighbours'
  get '/api/ports/alias', to: 'ports#api_port_alias', :as => 'api_port_aliases'
  get '/api/ports/type', to: 'ports#api_port_type', :as => 'api_port_type'
  get '/api/ports/utilisations', to: 'ports#api_port_utilisations', :as => 'api_port_utilisations'

  get '/api/ports', to: 'ports#api_index', :as => 'api_port'

  get '/hosts/on_subnet(.:format)', to: 'hosts#on_subnet', :constraints => { :q => @pcre }, :as => 'hosts_on_subnet'
  get '/hosts/:q', to: 'hosts#index', :constraints => { :q => @pcre }
  get '/hosts', to: 'hosts#index', :constraints => { :q => @pcre }, :as => 'hosts'
  get '/api/hosts/locations', to: 'hosts#api_host_locations', :as => 'api_hostnames_locations'
  get '/api/hostnames/list', to: 'hosts#api_hostnames', :as => 'autocomplete_hostname_list'
  get '/api/ip_addresses/list', to: 'hosts#api_ips', :as => 'autocomplete_ipaddress_list'
  get '/api/mac_addresses/list', to: 'hosts#api_macaddresses', :as => 'autocomplete_mac_address_list'
  get '/api/hosts', to: 'hosts#api_index', :as => 'api_host'

  get '/api/vlans/list', to: 'vlans#api_index', :as => 'autocomplete_vlan_list'
  get '/api/vlan_names/list', to: 'vlans#api_vlan_names', :as => 'autocomplete_vlan_name_list'

  get 'stats(.:format)/:metric' => 'stats#get',
    :constraints => { :metric => @pcre },
    :as => 'stats'
  get 'stats(.:format)/:metric/:prefix/:len' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/, :prefix => @ip, :len => /\d+/ },
    :as => 'subnet_stats'
  get 'stats(.:format)/:metric/:name' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/ },
    :as => 'subnet_stats_by_name'
  get 'stats(.:format)/:metric/:device' => 'stats#get',
    :constraints => { :metric => @pcre, :device => @pcre },
    :as => 'device_stats'
  get 'stats(.:format)/:metric/:source/:target' => 'stats#get',
    :constraints  => { :metric => /(owamp|bwctl)\.?.*/, :source => @pcre, :target => @pcre }
  get 'stats(.:format)/:metric/:device/:physical_port' => 'stats#get',
    :constraints  => { :device => @pcre, :metric => @pcre, :physical_port => @pcre },
    :as => 'port_stats'

  get 'render' => 'stats#proxy',
    :as => 'graphite_render'

  get 'graphs/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre }
  get 'graphs/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'grafana/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre },
    :as => 'grafana'
  get 'grafana/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'grafana/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'graphs.horizon/:metric' => 'd3s#horizon',
    :constraints => { :metric => @pcre }
  get 'graphs.horizon/:metric/:device' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:source/:target' => 'd3s#horizon', 
    :constraints => { :source => @pcre, :target => @pcre, :metric => /(owamp|bwctl)/ }
  get 'graphs.horizon/:metric/:device/:physical_port' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3/:p4' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'performance' => 'performances#index',
    :as => 'performance'
  get 'performance/wan/bandwidth' => 'performances#wan_bandwidth',
    :as => 'performance_wan_bandwidth'
  get 'performance/wan' => 'performances#wan',
    :as => 'wan_performances'
  get 'performance/lan' => 'performances#lan',
    :as => 'lan_performances'
  get 'performance/lan/campus' => 'performances#campus'

  get 'performance/services' => 'performances#services',
    :as => 'performance_services'
  get 'performance/visitor' => 'performances#visitor',
    :as => 'visitor_performances'
  get 'performance/slac-wireless' => 'performances#slac_wireless',
    :as => 'slac_wireless_performances'
    
  get 'performance/devices/temperatures' => 'performances#devices_temperature',
    :as => 'performance_devices_temperatures'
  get 'performance/devices/loss' => 'performances#devices_loss',
    :as => 'performance_devices_loss'

  get 'performance/devices' => 'performances#devices',
    :as => 'devices_dashboard'
  get 'performance/device/:device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'performance_device'
  get 'performance/device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'new_performance_device'
  get 'ping/:device' => 'performances#device_ping',
    :constraints => { :device => @pcre },
    :as => 'performance_device_ping'

  put 'delegate/port/:device/:physical_port' => 'ports#update',
      :constraints => { :device => @pcre, :physical_port => @pcre },
      :as => 'delegate_port'

  get 'performance/subnets' => 'performances#subnets',
    :as => 'subnets_dashboard'
  get '/performance/subnets/wheel', to: 'performances#subnet_wheel', :as => 'subnets_wheel'
  get 'performance/subnet/:prefix/:len' => 'performances#subnet',
    :as => 'performance_subnet',
    :constraints => { :prefix => @pcre }
    
  get '/api/subnets/list', to: 'subnets#api_subnet_name_list', :as => 'autocomplete_subnet_name_list'
  get '/api/subnet_graph', to: 'subnets#subnet_graph', :as => 'api_subnet_graph'
  get '/api/subnets', to: 'subnets#search', :as => 'api_subnets'
  get '/subnets/ips', to: 'subnets#ips', :as => 'subnet_ips'
  get '/subnets', to: 'subnets#index', :as => 'subnets'

  get '/api/telecoms/telephones', to: 'telecoms#api_telephones', :as => 'api_telephones'
  get '/telecoms/telephones', to: 'telecoms#telephones'

  get 'wireless/map' => 'wirelesses#map',
    :as => 'wirelessmap'
  get 'wireless/map/edit' => 'wirelesses#map'
  get 'wirelesses(.:format)' => 'wirelesses#index'
  post 'wirelesses(.:format)' => 'wirelesses#create'
  get 'wirelesses/new' => 'wirelesses#new',
    :as => 'new_wireless'
  get'wirelesses/:id/edit' => 'wirelesses#edit',
    :as => 'edit_wireless',
    :constraints => { :id => @id }
  get 'wirelesses/:id(.:format)' => 'wirelesses#show',
    :as => 'wireless',
    :constraints => { :id => @id }
  post 'wirelesses/:id(.:format)' => 'wirelesses#update',
    :constraints => { :id => @id }
  delete 'wirelesses/:id(.:format)' => 'wirelesses#destroy',
    :as => 'destroy_wireless',
    :constraints => { :id => @id }

  get 'topology' => 'topologies#index',
    :as => 'topology'
  get 'topologies/devices(.:format)' => 'topologies#devices',
    :as => 'topologies_devices'
  get 'topologies/hosts(.:format)' => 'topologies#hosts',
    :as => 'topologies_hosts'
  get 'topologies/vlans(.:format)' => 'topologies#vlans',
    :as => 'topologies_vlans'
    get 'topologies/subnets(.:format)' => 'topologies#subnets',
      :as => 'topologies_subnets'

  get 'neteng/transceivers(.:format)' => 'netengs#transceivers',
    :as => 'netengs_transceivers_paths'
  get 'neteng/uptimes(.:format)' => 'netengs#device_uptimes',
    :as => 'netengs_uptimes_paths'

  get 'acls/check(.:format)' => 'acls#check',
    :as => 'acl_check'
  get 'acls/list(.:format)' => 'acls#list',
    :as => 'acl_list'

  get 'cfm/search(.:format)' => 'cfms#search',
    :as => 'cfm'

  get 'api/techcoords/ports(.:format)' => 'techcoords#api_ports',
    :as => 'api_techcoords_ports',
    :constraints => { :device => @pcre }

app/models/subnet.rb
class Subnet < ActiveRecord::Base
end

app/controllers/subnets_controller.rb
require 'tree'
require 'ipaddr'

class SubnetsController < ApplicationController
  before_action :set_subnet, only: [:show, :edit, :update, :destroy]



  def autocomplete
    @subnets = Subnet.where autocomplete_params
  end

  # GET /subnets
  # GET /subnets.json
  def index
    respond_to do |format|
      format.html
      format.json { 
        @subnets = Subnet.all
      }
    end
  end
  
  def search
    @subnets = Subnet.where( 'vlan=?', vlan_params['vlan'] )
    render :template => 'subnets/index'
  end
  
  def api_subnet_name_list
    @subnets = Subnet.where autocomplete_params
  end
  
  def _subnet
    p = submit_params
    @s = nil
    if p['name']
      @s = Subnet.where( 'name = :name', p )
    elsif @p['prefix'] and p['netmask']
      @s = Subnet.where( 'prefix = :prefix AND netmask = :netmask', p )
    end
    @s.first
  end
  
  def ips
    
    @s = _subnet
    # get block
    # convert to cidr mask
    mask = IPAddr.new(@s['netmask']).to_i.to_s(2).count("1")
    @subnet = @s['prefix'] + '/' + mask.to_s
    #'134.79.230.0/24'
    @ips = IPAddr.new(@subnet).to_range
    # get arps
    @arps = {}
    # logger.info("SUBNET: %s" % (@subnet))
    Arp.where( 'ip_address << :subnet', { subnet: @subnet }).each do |a|
      ip = a.ip_address.to_s()
      unless @arps[ip]
        @arps[ip] = []
      end
      @arps[ip] << a
    end
  end
  
  def subnet_graph
    # order as { :name => 'blah', :children => [] }
    # use the :type as tree
    root = Tree::TreeNode.new('root')
    
    SubnetGraph.all.each do |i|

      next if i.name.nil? or [ "SPARE", "SPARE-IFZ", "SPARE-IFZLITE", "RESERVED FARM" ].include? i.name.upcase or i.name =~ /SPARE/
      
      pos = root # always start from root
      # logger.debug ">> #{i.name} #{i.types}"

      if i.types.any?
        i.types.each do |x|
          t = x.downcase
          n = Tree::TreeNode.new(t)
          # puts "  pos #{pos.name} => add (#{t})"

          has_already = false
          pos.children do |c|
            # puts "    comparing #{t} to #{c.name}"
            if t == c.name
              # logger.debug "    child #{t} already exists"
              has_already = true 
              n = c
            end
          end
          
          unless has_already
            # logger.debug "    creating new child #{n.name} with parent #{pos.name}"
            pos << n 
          end

          # ptr to next
          pos = n
        end
      end
      
      # add leaf of subnet name
      unless pos.name == "root"
        d = "#{i.prefix}/#{i.prefix_len}"
        # logger.debug "    adding leaf #{i.name.downcase} to #{pos.name}"
        begin
          pos << Tree::TreeNode.new( i.name.downcase, d )
        rescue
          # logger.debug("error")
        end
      end
      
    end
    
    render :json => root.as_json
  end
  
  
  private
  
    def autocomplete_params
      params.permit(:q)
    end

    def submit_params
      params.permit(:name,:prefix,:netmask,:prefix_len)
    end

    def vlan_params
      params.permit(:vlan)
    end

end

app/helpers/subnets_helper.rb
require 'ipaddr'

module SubnetsHelper

  def subnet_from_name( name )
    Subnet.where( 'name = ?', name )
  end
  
  def subnet_from_prefix( prefix, netmask )
    @s = Subnet.where( 'prefix = ? AND netmask = ?', name, netmask )
    @s.shift    
  end

  def subnet( p )
    if p['name']
      return subnet_from_name( p['name'] )
    elsif p['prefix'] and p['netmask']
      return subnet_from_prefix( p['prefix'], p['netmask'] )
    end
  end
  
  def netmask_to_prefix_len( mask )
    this = IPAddr.new( mask ).to_i.to_s(2).count("1")
    # logger.error("THIS: %s" % [this])
    this
  end
end

app/views/subnets/_form.html.erb
<%= form_for(@subnet) do |f| %>
  <% if @subnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subnet.errors.count, "error") %> prohibited this subnet from being saved:</h2>

      <ul>
      <% @subnet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subnets/edit.html.erb
<h1>Editing subnet</h1>

<%= render 'form' %>

<%= link_to 'Show', @subnet %> |
<%= link_to 'Back', subnets_path %>

app/views/subnets/index.html.erb
<div class="row-fluid span12">
  <div class="span1">
    <%= image_tag "three109.svg", :width=>48 %>
  </div>
  <div class="span11">
    <h1>Network Subnets</h1>
  </div>
</div>

<div class="row-fluid span12">

  <div class="span3">

    <div class="well sidebar-nav input-append">
        <input class="span10" placeholder="Filter..." type="text">
        <button class="btn add-on">
          <i class="icon-filter"></i>
        </button>
    </div>
  
    <div class="well sidebar-nav facet" for="netmask"></div>
    <div class="well sidebar-nav facet" for="routed_on"></div>

  </div>

  <div class="span9">
  
    <table class="dataTable table-striped table-bordered table-condensed table-hover"></table>

  </div>

  <div style="visibility: hidden">
    <div id="data_href"><%= subnets_path %></div>
    <div id="dataTables_swf">copy_cvs_xls_pdf.swf</div>
  </div>

</div>

<%= coffee_script_tag do %>

# ondocument
jQuery -> 

  # intiate any datatables we have
  oTable = $('.dataTable').dataTable
    # data
    sAjaxSource:  $('#data_href').text()
    sAjaxDataProp: ""
    bDeferRender: true
    # TODO: upgrade of datatables
    #  - mDataProp -> mData
    #  - fnRender -> mRender
    "aoColumns": [
      mDataProp: "name"
      sTitle: "Name"
      sDefaultContent: "-"
    ,
    #   mDataProp: "type"
    #   sTitle: "Type"
    #   sDefaultContent: "-"
    #   fnRender: (obj) -> 
    #     seen = obj.aData.type
    #     if obj.aData.type instanceof Array
    #       seen = obj.aData.type.join(', ')
    #     return seen.replace("-", "&#x2011;")
    # ,
      mDataProp: "prefix"
      sTitle: "Prefix"
      sDefaultContent: "-"
      sType: 'ip'
    ,
      mDataProp: "netmask"
      sTitle: "Netmask"
      sDefaultContent: "-"
    ,
      mDataProp: "default_gw"
      sTitle: "Gateway"
      sDefaultContent: "-"
      sType: 'ip'
    ,
      mDataProp: "vlan"
      sTitle: "Vlan"
      sDefaultContent: "-"
    ,
      mDataProp: "description"
      sTitle: "Description"
      sDefaultContent: "-"
    ,
      mDataProp: "routed_on"
      sTitle: "Router"
      sDefaultContent: "-"
      # fnRender: (obj) -> 
      #   seen = obj.aData.routed_on
      #   if obj.aData.routed_on instanceof Array
      #     seen = obj.aData.routed_on.join(', ')
      #   return seen.replace("-", "&#x2011;")
    ,
      mDataProp: "updated_at"
      sTitle: "Last Seen"
      sDefaultContent: "-"
      # fnRender: (obj) -> jQuery.timeago(row.last_seen)
      # return oldest
      sType: "seen"
      mRender: (obj,type,row) -> 
        seen = row.updated_at
        if row.updated_at instanceof Array
          seen = row.updated_at.sort()[0]
        if seen
          return jQuery.timeago(seen)
        return '-'
    ]
    # ui
    bProcessing: true
    bSort: true
    bJqueryUI:  true
    iDisplayLength: -1
    bAutoWidth: false
    # export types
    oTableTools:
      sSwfPath: $('.dataTables_swf').text()
    sDom:       '<"pull-left"i><"pull-right"T><"span12"t>r<"clear">'
    fnInitComplete: () ->
      createFacet()
    fnRowCallback: ( nRow, aData, iDisplayIndex, iDisplayIndexFull ) ->
      mapping = {
          'routed_on': 6,
      }
      for k,v of aData
        if typeIsArray v
          n = mapping[k]
          $('td:eq('+n+')', nRow).html( aData[k].join(', ') )

  createFacet = ->
    oTable.facets()

  $('input[type="text"]').keyup( () ->
      oTable.fnFilter( $(this).val() )
      oTable.fnUpdateFacets()
  )

  $('.facet').resizable(
      minHeight: 125,
      minWidth: 175,
      alsoResize: '.facet .facet-frame',
      # resize: (e,ui) ->
      #   ui.size.width = ui.originalSize.width
  )
  return


<% end %>

app/views/subnets/ips.html.erb
<div class="row-fluid span12">
  <h1>Subnet <%= @s.inspect %> Grid</h1>
</div>

<div class="row-fluid span12">


</div>

<ul>
  <% for i in @ips %>
    <li>
      <%= i.to_s() %>
      <% if @arps.has_key? i.to_s() %>
        <%= @arps[i.to_s()] %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= coffee_script_tag do %>

# ondocument
jQuery -> 

  console.log 'hello'

<% end %>

app/views/subnets/new.html.erb
<h1>New subnet</h1>

<%= render 'form' %>

<%= link_to 'Back', subnets_path %>

app/views/subnets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subnet_path(@subnet) %> |
<%= link_to 'Back', subnets_path %>