config/routes.rb
PtolemyWeb::Application.routes.draw do

  resources :replacements

  resources :hardwares

  @pcre = /[0-9A-Za-z\-\.\,\\\_\(\)\|\*\$\"\']+/
  @id = /[0-9A-Za-z]+/
  @mac = /[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}/
  @ip = /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/

  get '/devices/list', to: 'devices#list', :as => 'device_list'
  get '/devices/?(:device)?', to: 'devices#index', :constraints => { :device => @pcre }
  get '/devices', to: 'devices#index', :as => 'devices'
  get '/api/devices/neighbours', to: 'devices#api_device_neighbours', :as => 'api_device_neighbours'
  get '/api/devices/ipsla', to: 'devices#api_device_ipsla', :as => 'api_device_ipsla'
  get '/api/devices/vlans', to: 'devices#api_device_vlans', :as => 'api_device_vlans'
  get '/api/devices/list', to: 'devices#api_devices', :as => 'autocomplete_device_list'

  get '/ports/by_utilisation', to: 'ports#port_graphs_by_device', :constraints => { :device => @pcre }, :as => 'port_graphs_by_device'
  get '/ports/by_utilisation/:device', to: 'ports#port_graphs_by_device', :constraints => { :device => @pcre }
  get '/ports/by_uplinks', to: 'ports#port_graphs_by_uplinks', :constraints => { :device => @pcre }, :as => 'port_graphs_by_uplinks'

  get '/ports/location', to: 'ports#location', :as => 'port_location'
  get '/ports/:device', to: 'ports#index', :constraints => { :device => @pcre }
  get '/ports', to: 'ports#index', :constraints => { :device => @pcre }, :as => 'network_ports'

  get '/api/ports/neighbours', to: 'ports#api_port_neighbours', :as => 'api_port_neighbours'
  get '/api/ports/alias', to: 'ports#api_port_alias', :as => 'api_port_aliases'
  get '/api/ports/type', to: 'ports#api_port_type', :as => 'api_port_type'
  get '/api/ports/utilisations', to: 'ports#api_port_utilisations', :as => 'api_port_utilisations'

  get '/api/ports', to: 'ports#api_index', :as => 'api_port'

  get '/hosts/on_subnet(.:format)', to: 'hosts#on_subnet', :constraints => { :q => @pcre }, :as => 'hosts_on_subnet'
  get '/hosts/:q', to: 'hosts#index', :constraints => { :q => @pcre }
  get '/hosts', to: 'hosts#index', :constraints => { :q => @pcre }, :as => 'hosts'
  get '/api/hosts/locations', to: 'hosts#api_host_locations', :as => 'api_hostnames_locations'
  get '/api/hostnames/list', to: 'hosts#api_hostnames', :as => 'autocomplete_hostname_list'
  get '/api/ip_addresses/list', to: 'hosts#api_ips', :as => 'autocomplete_ipaddress_list'
  get '/api/mac_addresses/list', to: 'hosts#api_macaddresses', :as => 'autocomplete_mac_address_list'
  get '/api/hosts', to: 'hosts#api_index', :as => 'api_host'

  get '/api/vlans/list', to: 'vlans#api_index', :as => 'autocomplete_vlan_list'
  get '/api/vlan_names/list', to: 'vlans#api_vlan_names', :as => 'autocomplete_vlan_name_list'

  get 'stats(.:format)/:metric' => 'stats#get',
    :constraints => { :metric => @pcre },
    :as => 'stats'
  get 'stats(.:format)/:metric/:prefix/:len' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/, :prefix => @ip, :len => /\d+/ },
    :as => 'subnet_stats'
  get 'stats(.:format)/:metric/:name' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/ },
    :as => 'subnet_stats_by_name'
  get 'stats(.:format)/:metric/:device' => 'stats#get',
    :constraints => { :metric => @pcre, :device => @pcre },
    :as => 'device_stats'
  get 'stats(.:format)/:metric/:source/:target' => 'stats#get',
    :constraints  => { :metric => /(owamp|bwctl)\.?.*/, :source => @pcre, :target => @pcre }
  get 'stats(.:format)/:metric/:device/:physical_port' => 'stats#get',
    :constraints  => { :device => @pcre, :metric => @pcre, :physical_port => @pcre },
    :as => 'port_stats'

  get 'render' => 'stats#proxy',
    :as => 'graphite_render'

  get 'graphs/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre }
  get 'graphs/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'grafana/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre },
    :as => 'grafana'
  get 'grafana/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'grafana/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'graphs.horizon/:metric' => 'd3s#horizon',
    :constraints => { :metric => @pcre }
  get 'graphs.horizon/:metric/:device' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:source/:target' => 'd3s#horizon', 
    :constraints => { :source => @pcre, :target => @pcre, :metric => /(owamp|bwctl)/ }
  get 'graphs.horizon/:metric/:device/:physical_port' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3/:p4' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'performance' => 'performances#index',
    :as => 'performance'
  get 'performance/wan/bandwidth' => 'performances#wan_bandwidth',
    :as => 'performance_wan_bandwidth'
  get 'performance/wan' => 'performances#wan',
    :as => 'wan_performances'
  get 'performance/lan' => 'performances#lan',
    :as => 'lan_performances'
  get 'performance/lan/campus' => 'performances#campus'

  get 'performance/services' => 'performances#services',
    :as => 'performance_services'
  get 'performance/visitor' => 'performances#visitor',
    :as => 'visitor_performances'
  get 'performance/slac-wireless' => 'performances#slac_wireless',
    :as => 'slac_wireless_performances'
    
  get 'performance/devices/temperatures' => 'performances#devices_temperature',
    :as => 'performance_devices_temperatures'
  get 'performance/devices/loss' => 'performances#devices_loss',
    :as => 'performance_devices_loss'

  get 'performance/devices' => 'performances#devices',
    :as => 'devices_dashboard'
  get 'performance/device/:device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'performance_device'
  get 'performance/device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'new_performance_device'
  get 'ping/:device' => 'performances#device_ping',
    :constraints => { :device => @pcre },
    :as => 'performance_device_ping'

  put 'delegate/port/:device/:physical_port' => 'ports#update',
      :constraints => { :device => @pcre, :physical_port => @pcre },
      :as => 'delegate_port'

  get 'performance/subnets' => 'performances#subnets',
    :as => 'subnets_dashboard'
  get '/performance/subnets/wheel', to: 'performances#subnet_wheel', :as => 'subnets_wheel'
  get 'performance/subnet/:prefix/:len' => 'performances#subnet',
    :as => 'performance_subnet',
    :constraints => { :prefix => @pcre }
    
  get '/api/subnets/list', to: 'subnets#api_subnet_name_list', :as => 'autocomplete_subnet_name_list'
  get '/api/subnet_graph', to: 'subnets#subnet_graph', :as => 'api_subnet_graph'
  get '/api/subnets', to: 'subnets#search', :as => 'api_subnets'
  get '/subnets/ips', to: 'subnets#ips', :as => 'subnet_ips'
  get '/subnets', to: 'subnets#index', :as => 'subnets'

  get '/api/telecoms/telephones', to: 'telecoms#api_telephones', :as => 'api_telephones'
  get '/telecoms/telephones', to: 'telecoms#telephones'

  get 'wireless/map' => 'wirelesses#map',
    :as => 'wirelessmap'
  get 'wireless/map/edit' => 'wirelesses#map'
  get 'wirelesses(.:format)' => 'wirelesses#index'
  post 'wirelesses(.:format)' => 'wirelesses#create'
  get 'wirelesses/new' => 'wirelesses#new',
    :as => 'new_wireless'
  get'wirelesses/:id/edit' => 'wirelesses#edit',
    :as => 'edit_wireless',
    :constraints => { :id => @id }
  get 'wirelesses/:id(.:format)' => 'wirelesses#show',
    :as => 'wireless',
    :constraints => { :id => @id }
  post 'wirelesses/:id(.:format)' => 'wirelesses#update',
    :constraints => { :id => @id }
  delete 'wirelesses/:id(.:format)' => 'wirelesses#destroy',
    :as => 'destroy_wireless',
    :constraints => { :id => @id }

  get 'topology' => 'topologies#index',
    :as => 'topology'
  get 'topologies/devices(.:format)' => 'topologies#devices',
    :as => 'topologies_devices'
  get 'topologies/hosts(.:format)' => 'topologies#hosts',
    :as => 'topologies_hosts'
  get 'topologies/vlans(.:format)' => 'topologies#vlans',
    :as => 'topologies_vlans'
    get 'topologies/subnets(.:format)' => 'topologies#subnets',
      :as => 'topologies_subnets'

  get 'neteng/transceivers(.:format)' => 'netengs#transceivers',
    :as => 'netengs_transceivers_paths'
  get 'neteng/uptimes(.:format)' => 'netengs#device_uptimes',
    :as => 'netengs_uptimes_paths'

  get 'acls/check(.:format)' => 'acls#check',
    :as => 'acl_check'
  get 'acls/list(.:format)' => 'acls#list',
    :as => 'acl_list'

  get 'cfm/search(.:format)' => 'cfms#search',
    :as => 'cfm'

  get 'api/techcoords/ports(.:format)' => 'techcoords#api_ports',
    :as => 'api_techcoords_ports',
    :constraints => { :device => @pcre }

app/models/replacement.rb
class Replacement < ActiveRecord::Base
  belongs_to :entity
  belongs_to :hardware
  belongs_to :property
  belongs_to :replacement_hardware, class_name: "Hardware", :foreign_key => 'replacement_hardware_id'  
  
  #scope :old, where( 'updated_at < ?', Time.now - (2600*24*14) )
  
  # scope :device_like, lambda { |v| joins(:entity).where( entity.device => regexp ?, v  }
  
  def replacement_price
    if self.replacement_hardware and self.replacement_hardware.price and self.quantity
      self.replacement_hardware.price * self.quantity
    end
  end
  
  def replacement_date( refresh_time=5.years, now=Time.now )
    cycle = now
    if self.property and self.property.date_of_purchase
      cycle = self.property.date_of_purchase + refresh_time
    else
      cycle = now + refresh_time
    end

    if self.hardware and self.hardware.end_of_support
      if self.hardware.end_of_support < cycle
        # stupid time and date's
        cycle = self.hardware.end_of_support.to_time
      end
    end
    
    cycle
  end
    
  def replacement_time_delta( bin=1.year, refresh_time=5.years, now=Time.now )
    t = self.replacement_date(refresh_time=refresh_time,now=now)
    logger.error("T %s %s" % [t,now])
    u = t - now
    ( u.to_f / bin.to_f ).floor
  end
  
end

app/controllers/replacements_controller.rb
class ReplacementsController < ApplicationController
  before_action :set_replacement, only: [:show, :edit, :update, :destroy]

  # GET /replacements
  # GET /replacements.json
  def index
    @replacements = Replacement.all
  end

  # GET /replacements/1
  # GET /replacements/1.json
  def show
  end

  # GET /replacements/new
  def new
    @replacement = Replacement.new
  end

  # GET /replacements/1/edit
  def edit
  end

  # POST /replacements
  # POST /replacements.json
  def create
    @replacement = Replacement.new(replacement_params)

    respond_to do |format|
      if @replacement.save
        format.html { redirect_to @replacement, notice: 'Replacement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @replacement }
      else
        format.html { render action: 'new' }
        format.json { render json: @replacement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replacements/1
  # PATCH/PUT /replacements/1.json
  def update
    respond_to do |format|
      if @replacement.update(replacement_params)
        format.html { redirect_to @replacement, notice: 'Replacement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @replacement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replacements/1
  # DELETE /replacements/1.json
  def destroy
    @replacement.destroy
    respond_to do |format|
      format.html { redirect_to replacements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_replacement
      @replacement = Replacement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def replacement_params
      params.require(:replacement).permit(:entity__meta_id, :type, :quantity, :hardware_id, :replacement_id)
    end
end

app/helpers/replacements_helper.rb
module ReplacementsHelper
end

app/views/replacements/_form.html.erb
<%= form_for(@replacement) do |f| %>
  <% if @replacement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@replacement.errors.count, "error") %> prohibited this replacement from being saved:</h2>

      <ul>
      <% @replacement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entity__meta_id %><br>
    <%= f.text_field :entity__meta_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :hardware_id %><br>
    <%= f.text_field :hardware_id %>
  </div>
  <div class="field">
    <%= f.label :replacement_id %><br>
    <%= f.text_field :replacement_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replacements/edit.html.erb
<h1>Editing replacement</h1>

<%= render 'form' %>

<%= link_to 'Show', @replacement %> |
<%= link_to 'Back', replacements_path %>

app/views/replacements/index.csv.erb
# group,device,position,type,model,dob,eos,replacement_date,year_to_replace,replacement_model,quantity,cost
<% @replacements.each do |r| %>
<%= r.group_name %>,<%= r.entity.device.sub!('.slac.stanford.edu','') %>,<%= r.entity.relative_position %>,<%= r.entity.entity_type %>,<%= r.hardware.model if r.hardware %>,<%= r.property.date_of_purchase if r.property %>,<%= r.hardware.end_of_support if r.hardware %>,<%= r.replacement_date %>,<%= r.replacement_time_delta %>,<%= r.replacement_hardware.model if r.replacement_hardware %>,<%= r.quantity %>,<%= r.replacement_price %>
<% end %>

app/views/replacements/index.html.erb
<h1>Network Hardware Replacement Plan</h1>

<table cellpadding="0" cellspacing="0" border="0" class="dataTable table table-striped table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>Group</th>
      <th>Device</th>
			<th>Pos</th>
      <th>Type</th>
      <th>Model</th>
			<!-- <th>Serial (hw/property)</th> -->
			<th>DOB</th>
      <th>EOS</th>
			<th>Replacement Date</th>
      <th>Model</th>
      <th>No.</th>
      <th>Cost</th>
      <!-- <th>Edit</th>
      <th>Del</th> -->
    </tr>
  </thead>

  <tbody>
    <% @replacements.each do |r| %>
      <tr>
        <td><%= r.id %></td>
        <td><%= r.group_name %></td>
        <td><%= r.entity.device.sub!('.slac.stanford.edu','') %></td>
        <td><%= r.entity.relative_position %></td>
        <td><%= r.entity.entity_type %></td>
        <td><%= r.hardware.model if r.hardware %></td>
        <!-- <td><%= r.entity.serial %> / <% r.property.serial if r.property %></td> -->
				<td><%= r.property.date_of_purchase.strftime("%Y-%m-%d") if r.property %></td>
        <td><%= r.hardware.end_of_support if r.hardware %></td>
        <td><%= r.replacement_date.strftime("%Y-%m-%d") %></td>
        <td><%= r.replacement_hardware.model if r.replacement_hardware %></td>
        <td><%= r.quantity %></td>
        <td><%= r.replacement_price %></td>
        <!-- <td><%= link_to 'Edit', edit_replacement_path(r) %></td>
        <td><%= link_to 'Del', r, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Replacement', new_replacement_path %> -->


<%= coffee_script_tag do %>
jQuery ->
	
  oTable = $('.dataTable').dataTable
    iDisplayLength: -1
    bSort: true
    aaSorting: [ [2,'asc'], [3,'asc'] ]
    bJqueryUI:  true
    bAutoWidth: false
    sDom: "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>"

<% end %>

app/views/replacements/new.html.erb
<h1>New replacement</h1>

<%= render 'form' %>

<%= link_to 'Back', replacements_path %>

app/views/replacements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entity  meta:</strong>
  <%= @replacement.entity__meta %>
</p>

<p>
  <strong>Type:</strong>
  <%= @replacement.type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @replacement.quantity %>
</p>

<p>
  <strong>Hardware:</strong>
  <%= @replacement.hardware %>
</p>

<p>
  <strong>Replacement:</strong>
  <%= @replacement.replacement %>
</p>

<%= link_to 'Edit', edit_replacement_path(@replacement) %> |
<%= link_to 'Back', replacements_path %>