config/routes.rb
  get '/ports/by_uplinks', to: 'ports#port_graphs_by_uplinks', :constraints => { :device => @pcre }, :as => 'port_graphs_by_uplinks'

  get '/ports/location', to: 'ports#location', :as => 'port_location'
  get '/ports/:device', to: 'ports#index', :constraints => { :device => @pcre }
  get '/ports', to: 'ports#index', :constraints => { :device => @pcre }, :as => 'network_ports'

  get '/api/ports/neighbours', to: 'ports#api_port_neighbours', :as => 'api_port_neighbours'
  get '/api/ports/alias', to: 'ports#api_port_alias', :as => 'api_port_aliases'
  get '/api/ports/type', to: 'ports#api_port_type', :as => 'api_port_type'
  get '/api/ports/utilisations', to: 'ports#api_port_utilisations', :as => 'api_port_utilisations'

  get '/api/ports', to: 'ports#api_index', :as => 'api_port'

  get '/hosts/on_subnet(.:format)', to: 'hosts#on_subnet', :constraints => { :q => @pcre }, :as => 'hosts_on_subnet'
  get '/hosts/:q', to: 'hosts#index', :constraints => { :q => @pcre }
  get '/hosts', to: 'hosts#index', :constraints => { :q => @pcre }, :as => 'hosts'
  get '/api/hosts/locations', to: 'hosts#api_host_locations', :as => 'api_hostnames_locations'
  get '/api/hostnames/list', to: 'hosts#api_hostnames', :as => 'autocomplete_hostname_list'
  get '/api/ip_addresses/list', to: 'hosts#api_ips', :as => 'autocomplete_ipaddress_list'
  get '/api/mac_addresses/list', to: 'hosts#api_macaddresses', :as => 'autocomplete_mac_address_list'
  get '/api/hosts', to: 'hosts#api_index', :as => 'api_host'

  get '/api/vlans/list', to: 'vlans#api_index', :as => 'autocomplete_vlan_list'
  get '/api/vlan_names/list', to: 'vlans#api_vlan_names', :as => 'autocomplete_vlan_name_list'

  get 'stats(.:format)/:metric' => 'stats#get',
    :constraints => { :metric => @pcre },
    :as => 'stats'
  get 'stats(.:format)/:metric/:prefix/:len' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/, :prefix => @ip, :len => /\d+/ },
    :as => 'subnet_stats'
  get 'stats(.:format)/:metric/:name' => 'stats#get',
    :constraints  => { :metric => /subnet\..*/ },
    :as => 'subnet_stats_by_name'
  get 'stats(.:format)/:metric/:device' => 'stats#get',
    :constraints => { :metric => @pcre, :device => @pcre },
    :as => 'device_stats'
  get 'stats(.:format)/:metric/:source/:target' => 'stats#get',
    :constraints  => { :metric => /(owamp|bwctl)\.?.*/, :source => @pcre, :target => @pcre }
  get 'stats(.:format)/:metric/:device/:physical_port' => 'stats#get',
    :constraints  => { :device => @pcre, :metric => @pcre, :physical_port => @pcre },
    :as => 'port_stats'

  get 'render' => 'stats#proxy',
    :as => 'graphite_render'

  get 'graphs/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre }
  get 'graphs/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'grafana/:metric' => 'grafanas#index',
    :constraints => { :metric => @pcre },
    :as => 'grafana'
  get 'grafana/:metric/:device/:physical_port' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'grafana/:metric/:device/:p1/:p2' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'grafana/:metric/:device/:p1/:p2/:p3/:p4' => 'grafanas#port', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'graphs.horizon/:metric' => 'd3s#horizon',
    :constraints => { :metric => @pcre }
  get 'graphs.horizon/:metric/:device' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:source/:target' => 'd3s#horizon', 
    :constraints => { :source => @pcre, :target => @pcre, :metric => /(owamp|bwctl)/ }
  get 'graphs.horizon/:metric/:device/:physical_port' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre, :physical_port => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }
  get 'graphs.horizon/:metric/:device/:p1/:p2/:p3/:p4' => 'd3s#horizon', 
    :constraints => { :device => @pcre, :metric => @pcre }

  get 'performance' => 'performances#index',
    :as => 'performance'
  get 'performance/wan/bandwidth' => 'performances#wan_bandwidth',
    :as => 'performance_wan_bandwidth'
  get 'performance/wan' => 'performances#wan',
    :as => 'wan_performances'
  get 'performance/lan' => 'performances#lan',
    :as => 'lan_performances'
  get 'performance/lan/campus' => 'performances#campus'

  get 'performance/services' => 'performances#services',
    :as => 'performance_services'
  get 'performance/visitor' => 'performances#visitor',
    :as => 'visitor_performances'
  get 'performance/slac-wireless' => 'performances#slac_wireless',
    :as => 'slac_wireless_performances'
    
  get 'performance/devices/temperatures' => 'performances#devices_temperature',
    :as => 'performance_devices_temperatures'
  get 'performance/devices/loss' => 'performances#devices_loss',
    :as => 'performance_devices_loss'

  get 'performance/devices' => 'performances#devices',
    :as => 'devices_dashboard'
  get 'performance/device/:device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'performance_device'
  get 'performance/device' => 'grafanas#device',
    :constraints => { :device => @pcre },
    :as => 'new_performance_device'
  get 'ping/:device' => 'performances#device_ping',
    :constraints => { :device => @pcre },
    :as => 'performance_device_ping'

  put 'delegate/port/:device/:physical_port' => 'ports#update',
      :constraints => { :device => @pcre, :physical_port => @pcre },
      :as => 'delegate_port'

  get 'performance/subnets' => 'performances#subnets',
    :as => 'subnets_dashboard'
  get '/performance/subnets/wheel', to: 'performances#subnet_wheel', :as => 'subnets_wheel'
  get 'performance/subnet/:prefix/:len' => 'performances#subnet',
    :as => 'performance_subnet',
    :constraints => { :prefix => @pcre }
    
  get '/api/subnets/list', to: 'subnets#api_subnet_name_list', :as => 'autocomplete_subnet_name_list'
  get '/api/subnet_graph', to: 'subnets#subnet_graph', :as => 'api_subnet_graph'
  get '/api/subnets', to: 'subnets#search', :as => 'api_subnets'
  get '/subnets/ips', to: 'subnets#ips', :as => 'subnet_ips'
  get '/subnets', to: 'subnets#index', :as => 'subnets'

  get '/api/telecoms/telephones', to: 'telecoms#api_telephones', :as => 'api_telephones'
  get '/telecoms/telephones', to: 'telecoms#telephones'

  get 'wireless/map' => 'wirelesses#map',
    :as => 'wirelessmap'
  get 'wireless/map/edit' => 'wirelesses#map'
  get 'wirelesses(.:format)' => 'wirelesses#index'
  post 'wirelesses(.:format)' => 'wirelesses#create'
  get 'wirelesses/new' => 'wirelesses#new',
    :as => 'new_wireless'
  get'wirelesses/:id/edit' => 'wirelesses#edit',
    :as => 'edit_wireless',
    :constraints => { :id => @id }
  get 'wirelesses/:id(.:format)' => 'wirelesses#show',
    :as => 'wireless',
    :constraints => { :id => @id }
  post 'wirelesses/:id(.:format)' => 'wirelesses#update',
    :constraints => { :id => @id }
  delete 'wirelesses/:id(.:format)' => 'wirelesses#destroy',
    :as => 'destroy_wireless',
    :constraints => { :id => @id }

  get 'topology' => 'topologies#index',
    :as => 'topology'
  get 'topologies/devices(.:format)' => 'topologies#devices',
    :as => 'topologies_devices'
  get 'topologies/hosts(.:format)' => 'topologies#hosts',
    :as => 'topologies_hosts'
  get 'topologies/vlans(.:format)' => 'topologies#vlans',
    :as => 'topologies_vlans'
    get 'topologies/subnets(.:format)' => 'topologies#subnets',
      :as => 'topologies_subnets'

  get 'neteng/transceivers(.:format)' => 'netengs#transceivers',
    :as => 'netengs_transceivers_paths'
  get 'neteng/uptimes(.:format)' => 'netengs#device_uptimes',
    :as => 'netengs_uptimes_paths'

  get 'acls/check(.:format)' => 'acls#check',
    :as => 'acl_check'
  get 'acls/list(.:format)' => 'acls#list',
    :as => 'acl_list'

  get 'cfm/search(.:format)' => 'cfms#search',
    :as => 'cfm'

  get 'api/techcoords/ports(.:format)' => 'techcoords#api_ports',
    :as => 'api_techcoords_ports',
    :constraints => { :device => @pcre }
  get 'techcoords/ports/:device' => 'techcoords#ports',
    :constraints => { :device => @pcre }
  get 'techcoords/ports' => 'techcoords#ports',
    :as => 'techcoords_ports',
    :constraints => { :device => @pcre }

  get 'api/techcoords/locations(.:format)' => 'techcoords#api_locations',
    :as => 'api_techcoords_locations',
    :constraints => { :hostname => @pcre }
    get 'techcoords/locations/:hostname' => 'techcoords#locations',
      :constraints => { :hostname => @pcre }
  get 'techcoords/locations' => 'techcoords#locations',
    :as => 'techcoords_locations',
    :constraints => { :hostname => @pcre }
  
  
  get 'home', :to => 'static#home'
  get 'netops', :to => 'static#netop'
  get 'techcoords', :to => 'static#techcoord'
  get 'itds', :to => 'static#itds'
  get 'telecoms', :to => 'static#telecom'
  get 'internals', :to => 'static#internal'
  get 'mccs', :to => 'static#mcc'
  get 'cybers', :to => 'static#cyber'
  get 'beta', :to => 'static#beta'
  
  root :to => 'static#home'

  resources :physical_securities

  resources :datacenters

  resources :helpdesks
  resources :techcoords
  

app/models/topology.rb
class Topology < ActiveRecord::Base
end

app/controllers/topologies_controller.rb
require 'ipaddr'

class TopologiesController < ApplicationController

  def index
    # @topologies = Topology.all
    render :template => 'topologies/index'
  end


  def devices
    p = devices_params
    neighbours = L1_Neighbour.where 'device ~ ?', p['device']
    @nodes, @links = graph( neighbours, 'device' )
    render :template => 'topologies/paths'
  end
  
  def hosts
    p = host_params
    @nodes = []
    @links = []
    p.each do |k,v|
      neighbours = CachedHost.where( k+" = ?", v )
      n,l = graph( neighbours, 'host' )
      @nodes.push(*n)
      @links.push(*l)
    end
    render :template => 'topologies/paths'
  end

  def vlans
    p = vlan_params
    @nodes = []
    @links = []

    devices = []
    if p.include? :vlan and ! p['vlan'].nil?
      devices = Vlan.where( 'vlan = ?', p['vlan']).map{ |v| v['device'] }
    elsif p.include? :vlan_name and ! p['vlan_name'].nil?
      devices = Vlan.where( 'name ~ ?', p['vlan_name']).map{ |v| v['device'] }
    end
    
    # logger.info 'neighbours (%s): %s' % [neighbours.size, neighbours]
    n, l = graph( prune( devices ), 'device' )
    @nodes.push(*n)
    @links.push(*l)
    
    render :template => 'topologies/paths'
  end

  def subnets
    p = subnet_params
    @nodes = []
    @links = []

    neighbours = []
    
    cidr = []
    
    if p.has_key? 'subnet'
      Subnet.where( 'name ~ ?', p['subnet'] ).each do |subnet|
        cidr.push '%s/%s' % [subnet['prefix'].to_s, IPAddr.new(subnet['netmask'].to_s).to_i.to_s(2).count("1") ]
      end
    end
    
    if p.has_key? 'cidr'
      cidr << p['cidr']
    end

    cidr.each do |c|
      neighbours = CachedHost.where( "ip_address::inet << ?", c )
      n,l = graph( neighbours, 'host' )
      @nodes.push(*n)
      @links.push(*l)
    end
    
    # add device to device links
    n, l = graph( prune( @nodes ), 'device' )
    @nodes.push(*n)
    @links.push(*l)
    
    render :template => 'topologies/paths'
  end


  private

    # given an array of items, convert to a graph suitable
    def graph( items, type )
      
      @these_nodes = []
      links = []

      def _do( name )
        unless @these_nodes.include? name
          @these_nodes << name
        end
        name
      end
      
      items.each do |i|
        
        if type == 'device'
          s = _do( i['device'].downcase )
          t = _do( i['peer_device'].downcase )
          links << { 'source' => s, 'target' => t, 'source_port' => i['physical_port'], 
            'target_port' => i['peer_physical_port'], 'speed' => i['speed'].to_i }
          links << { 'source' => t, 'target' => s, 'source_port' => i['peer_physical_port'], 
            'target_port' => i['physical_port'], 'speed' => i['speed'].to_i }

        elsif type == 'host'

          unless i[:hostname].nil?
            s = _do( i['hostname'].downcase )
          else
            s = _do( i['ip_address'].gsub( '.', '_' ) )
          end
          
          unless i[:device].nil?
            t = _do( i['device'].downcase )
            links << { 'source' => s, 'target' => t, 'source_port' => 'nic', 
              'target_port' => i['physical_port'], 'speed' => i['data']['speed'].to_i }
            links << { 'source' => t, 'target' => s, 'source_port' => i['physical_port'], 
              'target_port' => 'nic', 'speed' => i['data']['speed'].to_i }
          end
          
        else
          
          raise 'unsupported topology peer type ' + type

        end
        
      end
      
      return @these_nodes, links
    end

    # prune
    # TODO: actually determine the spanning tree too; ie if the link as the vlan trunked
    def prune( devices )
      # all neighbours
      all_neighbours = L1_Neighbour.where 'device in (?)', devices
      # remove those not in vlan tree
      neighbours = []
      all_neighbours.each do | n |
        if devices.include? n['peer_device'] and devices.include? n['device']
          neighbours << n
        end
      end
      return neighbours
    end


    def topology_params
      params[:topology]
    end
    
    def devices_params
      params.permit( :device )
    end

    def host_params
      params.permit( :hostname, :ip_address, :mac_address )
    end
    
    def vlan_params
      params.permit( :vlan, :vlan_name )
    end
   
    def subnet_params
      params.permit( :cidr, :subnet )
    end
    
end

app/helpers/topologies_helper.rb
module TopologiesHelper
    
end

app/views/topologies/_form.html.erb
<%= form_for(@topology) do |f| %>
  <% if @topology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topology.errors.count, "error") %> prohibited this topology from being saved:</h2>

      <ul>
      <% @topology.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topologies/edit.html.erb
<h1>Editing topology</h1>

<%= render 'form' %>

<%= link_to 'Show', @topology %> |
<%= link_to 'Back', topologies_path %>

app/views/topologies/index.html.erb
<div class="row row-fluid">
  <div class="row span12" style="vertical-align: middle">
    <div class="span2">
      <h1>Topology</h1>
    </div>
    <div class="input-prepend center">
      <form class="form-inline" id="find" autocomplete="off">
        <div id="type" class="btn-group">
          <a id="search_type" class="btn"><span id="dropdown-text">device</span></button>
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a data="devices.json" placeholder="switch or router name">device</a></li>
            <li class="divider"></li>
            <li><a data="hosts.json" placeholder="hostname of computer">hostname</a></li>
            <li><a data="hosts.json" placeholder="mac address of host">mac_address</a></li>
            <li><a data="hosts.json" placeholder="ip address of host">ip_address</a></li>
            <li class="divider"></li>
            <li><a data="subnets.json" placeholder="subnet cidr">cidr</a></li>
            <li><a data="subnets.json" placeholder="subnet name">subnet</a></li>
            <li class="divider"></li>
            <li><a data="vlans.json" placeholder="vlan number">vlan</a></li>
            <li><a data="vlans.json" placeholder="vlan/subnet name">vlan_name</a></li>
          </ul>
        </div>
        <input type="text" id="autocomplete" class="input-wrapper" autocomplete="off"></input>
      </form>
    </div>
    <div class="input-append pull-right">
      <input id="link_distance" type="text" value="120" class="input-small span2"></input>
      <button class="btn" id="clear_button">Clear</button>
      <button class="btn" id="repulsion">Repulse</button>
      <button class="btn" id="update">Update</button>
    </div>
  </div>

  <div class="row-fluid span12">
      <div class="TOPOLOGY" id="d3_viz"></div>
  </div>
</div>

<%= coffee_script_tag do %>
_repulse = true

fill_window "#d3_viz"
TOPOLOGY = new TopologyPane( "#d3_viz" )
TYPE = null
LINK = null

$('form#find > div#type > ul.dropdown-menu > li > a').on 'click', (e)->
  TYPE = this.text
  LINK = $(this).attr("data")
  # update the dropbox box value
  $("#search_type > span#dropdown-text").text( TYPE )
  # clear text
  $('input#autocomplete').text('blah').attr('placeholder', $(this).attr("placeholder") )


# initiate first item
$('form#find > div#type > ul.dropdown-menu > li > a').first().trigger('click')

# autocomplete
$('#autocomplete').typeahead(
  source: (q,process) ->
    $.get( '/api/' + pluralise( TYPE ) + '/list', { query: q }, (d) ->
      process( d )
    )
)

$('#find').submit () ->
  uri = '/topologies/' + LINK + '?' + TYPE + '=' + encodeURIComponent($('.input-wrapper').val())
  console.log uri
  TOPOLOGY.fetch( uri )
  return false

$('#link_distance').bind( "propertychange keyup input paste", (ev) ->
  TOPOLOGY.link_distance( $(this).val() )
)

$('#clear_button').on( "click", () ->
  console.log('clearing all')
  n = TOPOLOGY.num_nodes()
  t = n/10000
  i = 0
  while i < n
    setTimeout( () ->
        TOPOLOGY.delete_node TOPOLOGY.NODES[0]
    , t*i
    )
    i++
)

$('#repulsion').on("click", () ->
  if this.value == 'repulse'
    this.value = 'static'
    TOPOLOGY.stop()
    _repulse = false
  else
    this.value = 'repulse'
    TOPOLOGY.start
    _repulse = true
)

# update the link stats
$('#update').on("click", () ->
  i = 0
  while i<LINKS.length
    TOPOLOGY.get_link( LINKS[i])
    i++
)

<% end %>

app/views/topologies/new.html.erb
<h1>New topology</h1>

<%= render 'form' %>

<%= link_to 'Back', topologies_path %>

app/views/topologies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_topology_path(@topology) %> |
<%= link_to 'Back', topologies_path %>